### ISSUE TITLE
Unable to import nonechucks

### ISSUE THREAD

**Issue by sannawag** [msamogh/nonechucks#1]
Hello, 

I get the following error when trying to load nonechucks (after installing either with pip or cloning) in Python 3.6.3:

>>> import nonechucks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/nonechucks/__init__.py", line 1, in <module>
    from dataset import *
ModuleNotFoundError: No module named 'dataset'

Thank you!

**Comment by msamogh** [comment]
Hi @sannawag,
It looks like the import in `__init__.py` was using the Python2 syntax. I've replaced it with Python3 compatible relative import now (a0f846c68458ef2c5d6742aedede90b8c56bb1b0)

The library was written and tested on Python2. I'll be running tests for Python3 over the course of the next few days. Please open an issue if you encounter anything else.
