### ISSUE TITLE
Overriding torch's classes

### ISSUE THREAD

**Issue by shigabeev** [msamogh/nonechucks#12]
After importing module, it overrides torch's dataloader so that in no longer can accept another datasets. :(
<img width="1004" alt="Screen Shot 2019-05-12 at 4 39 55 PM" src="https://user-images.githubusercontent.com/9149327/57589155-b7f9c900-74d4-11e9-97eb-72957e547166.png">

**Comment by msamogh** [comment]
Could you paste the surrounding code (before/after the initializing the `DataLoader`s). Also, if you could include the relevant imports as well, it'd be great!

**Comment by msamogh** [comment]
Closing due to no further info.
