### ISSUE TITLE
Override some functions of the original dataset

### ISSUE THREAD

**Issue by yanxu1per** [msamogh/nonechucks#14]
Hi, thank you for your work.
I am using nonechucks to deal with bad examples. However, in my original dataset class, one function get_img_info is defined. After using nc.SafeDataset to wrap it, it shows, 'SafeDataset object has no attribute 'get_img_info'

**Comment by yanxu1per** [comment]
Before that, I change _DataLoaderIter to _BaseDataLoaderIter in your code because the former one doesn't exist in my torch version (1.1.0). Weird

**Comment by msamogh** [comment]
Thanks for raising the issue. It's been fixed now. https://github.com/msamogh/nonechucks/commit/26382f087000291ce781a0bb213259806337cc96
