### ISSUE TITLE
How to handle TypError using nonechucks

### ISSUE THREAD

**Issue by simongeek** [msamogh/nonechucks#9]
Hi,

How to handle TypeError using nonechucks?

I have 162400 annotations (260 labels per one annotation) in json file. Each annotation contains filename for example aaa.jpg. I load photos based on filename from annotation json file. My image dataset contains 162000 images, so I do not have 400 photos in the collection. If the dataloader comes across the name of the annotation image and is not in the image set, it returns TypeError to me.
Do you know how to catch this error using your library? I tried SafeDataLoader and it does not work.
I also tried try except, but if I print a picture as None, I get a Class TypeNone error.
Best!

**Comment by msamogh** [comment]
Are you using the SafeDataloader in conjunction with the SafeDataset?

**Comment by simongeek** [comment]
Yes, I also tried separately and it does not work.

**Comment by simongeek** [comment]
Can I replace in class SimpleCustomDataset(Dataset) to SimpleCustomDataset(nc.SafeDataset)?

**Comment by msamogh** [comment]
You can do
`custom_dataset = SimpleCustomDataset()
safe_custom_dataset = nc.SafeDataset(custom_dataset)`

**Comment by simongeek** [comment]
when I try:

```
mvc_dataset = MVCDataset(json_file="labels.json",
                         root="data", transform=transform, target_transform=None)

save_mvc_dataset = nc.SafeDataset(mvc_dataset)
```
I got TypeError: TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'NoneType'>

**Comment by msamogh** [comment]
Could you paste your full stack trace?

**Comment by msamogh** [comment]
Closing due to no response.
